title: 黑境
subtitle: aak1247的博客
url: https://aak1247.coding.me/
root: /
  
author: aak1247
description: Still waters run deep
avatar: /images/avatar.gif
language: zh-Hans
duoshuo_shortname: aak1247
permalink: :title.html

sitemap: 
  path: sitemap.xml
baidusitemap: 
  path: baidusitemap.xml

search: 
  path: search.xml
  field: post
  format: html
  limit: 10000

html_minifier:
  enable: true
  exclude: 

css_minifier:
  enable: true
  exclude: 
    - '*.min.css'

js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude: 
    - '*.min.js'

image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false