{
  "name": "无境之境",
  "title": "无境之境",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.2"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-server": "^0.2.0"
  },
   "author": "aak1247",
   "description": "Still waters run deep",
   "avatar": "/images/avatar.gif",
   "language": "zh-Hans",
   "duoshuo_shortname": "aak1247",
   "algolia": {
           "applicationID": "D9H213A3K8",
           "apiKey": "47184ccb2710976142b165ae9dc1eb32",
           "adminApiKey": "ddf1627ad4d52e80d78265e425a7c649",
           "indexName": "blog_PAGE",
           "chunkSize": "5000"
   },
   "baidu-site-verification": "<meta name="baidu-site-verification" content="UX9g1c87KX" />",
   "sitemap": {
      "path": "sitemap.xml"
   },
   "baidusitemap": {
     "path": "baidusitemap.xml"
   }
}
