title: 黑境
subtitle: aak1247的博客
url: https://aak1247.coding.me/
root: /
  
author: aak1247
description: Still waters run deep
avatar: /images/avatar.gif
language: zh-Hans
duoshuo_shortname: aak1247

algolia: 
  applicationID: D9H213A3K8
  apiKey: 47184ccb2710976142b165ae9dc1eb32
  adminApiKey: ddf1627ad4d52e80d78265e425a7c649
  indexName: blog_PAGE
  chunkSize: 5000
  fields: 
    - title
    - slug
    - content:strip

sitemap: 
  path: sitemap.xml
baidusitemap: 
  path: baidusitemap.xml

search: 
  path: search.xml
  field: post
  format: html
  limit: 10000

